name: "Formatting check"
on:
  pull_request:
  push:
jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: Rishabh510/Path-lister-action@1.0
      id: files
      with:
        path: "."
        type: ".nix"
    - uses: workflow/nix-shell-action@v3
      with:
        packages: nixfmt
        script: |
          for changed_file in ${{ steps.files.outputs.paths }}; do
            if [ "${changed_file: -4}" == ".nix" ]; then
              nixfmt --check "${changed_file}";
            fi
          done
